# ==========================================
# CONFIGURACIÓN BÁSICA
# ==========================================
spring.application.name=pedido
server.port=8083

# ==========================================
# BASE DE DATOS MYSQL - AIVEN
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Forzar el dialecto para evitar el error del log
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Esto ayuda a que Spring no falle si la conexión tarda un poco
spring.datasource.hikari.initialization-fail-timeout=0
# ==========================================
# SEGURIDAD JWT
# ==========================================
# Clave secreta (debe tener al menos 32 caracteres para HS256)
jwt.secret=${JWT_SECRET}
# Expiración: 86400000 ms = 24 horas
jwt.expiration=86400000

# ==========================================
# CONFIGURACIÓN DE LOGS
# ==========================================
logging.level.com.syncro.pedido=DEBUG

# ==========================================
# CONFIGURACIÓN RABBITMQ (CloudAMQP)
# ==========================================
# Reemplaza con tus credenciales de CloudAMQP
spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USER}
spring.rabbitmq.password=${RABBIT_PASS}
spring.rabbitmq.virtual-host=${RABBIT_VHOST}

# ==========================================
# PERFIL ACTIVO
# ==========================================
spring.profiles.active=dev

